### PR TITLE
added instructions from main NSS repo

### PR DESCRIPTION
**Pull request by markellisdev**
##Pull Requests

##Descriptions:

* Please describe what issue this PR solves
This adds the instructions for the project exactly as they were written from the NSS master.

I added here so that we do not have to go back to the main repo to learn what we need to complete.

##Steps to Test:

Nothing needed to test, just helpful to have here in the project.

##System configuration.

* Are there 3rd party libraries that need to be installed?
None

* Any command line utilities to run?
None

### CODE REVIEW

**Comment by richievs91** [comment]
👍

**Review by TrentHand — COMMENTED** [review]
👍

**Comment by ZacharyCline** [comment]
Thanks for that!

**Comment by ZacharyCline** [comment]
🚀

**Pull request merged**
