### PR TITLE
Fixed Buy Product Button

### PR DESCRIPTION
**Pull request by ZacharyCline**
## Descriptions:

Product_Detail Now has a working buy product button. It will add a product to an active order or it will add a product to a new order. Reflects in db. After adding it redirects you to the products page to continue shopping.

## Steps to Test:
git fetch 
git checkout zc-helper
Makemigrations, Migrate
go to webstore/products.
pick a product and click the buy button
check your db to see if the orderitems has been updated.

### CODE REVIEW

**Comment by richievs91** [comment]
👍 Awesome!

**Comment by ZacharyCline** [comment]
You had all the work done bro, i just helped configure some little parts of it.

**Review by markellisdev — CHANGES_REQUESTED** [review]
Product is being added, but each add product is creating a new order id.

**Review by markellisdev — APPROVED** [review]

**Comment by markellisdev** [comment]
Working now, just needs new customer login. You cannot use fixtures for User or Customer

**Pull request merged**
